# run Unit test
language: android
android:
    components:
        - tools
        - platform-tools
        - tools
        - build-tools-23.0.3
        - android-23

script:
   - ./gradlew jacocoTestReport


after_success:
    - bash <(curl -s https://codecov.io/bash)