# run Unit test
language: android
android:
    components:
        - tools
        - build-tools-23.0.1
        - android-23
        - tools
        - platform-tools

script:
   - ./gradlew jacocoTestReport


after_success:
    - bash <(curl -s https://codecov.io/bash)