# run Unit test
language: android
    android:
        components:
            - tools
            - platform-tools
            - tools
            - build-tools-25.0.1
            - android-25

script:
   - ./gradlew jacocoTestReport


after_success:
    - bash <(curl -s https://codecov.io/bash)
